image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build -t test -f files/blueChip-Dockerfile .
    - docker build -t test -f files/blueChip-api-Dockerfile .
